version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/gradle"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"    
  
  - package-ecosystem: "maven"
    directory: "/maven"
    schedule:
      interval: "daily"    
