version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
   - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1000
    schedule:
      interval: "daily"
